[package]
name    = "swiedowski_engine"
version = "1.0.0"
edition = "2021"

[workspace]
members = [
	"math",
	"render",
]

[dependencies]
math    = {path = "math"}
render  = {path = "render"}
image = "0.24"

[profile.dev]
opt-level = 1
