[package]
name    = "swiedowski_engine"
version = "1.0.0"
edition = "2021"


[dependencies]
math    = {path = "../math"}
render  = {path = "../render"}
noise   = {path = "../rand_noise"}
image = "0.24"

[profile.dev]
opt-level = 1
