[done]
wave_noise = 1.0
complex_n  = 0.2
bubble     = 0.1
random     = 0.1
quaternion = 0.2

[todo]
quaternion_op = 0.5
perlin_noise  = 2.0
expand_image  = 2.0
renderer      = 3.0
math_refactor = 5.0
